config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :boardgames
  #get 'home/index'
  get 'home/about'
  root 'boardgames#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/boardgame.rb
class Boardgame < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :boardgames
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boardgames_controller.rb
class BoardgamesController < ApplicationController
  before_action :set_boardgame, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /boardgames or /boardgames.json
  def index
    @boardgames = Boardgame.all
  end

  # GET /boardgames/1 or /boardgames/1.json
  def show
  end

  # GET /boardgames/new
  def new
    #@boardgame = Boardgame.new
    @boardgame = current_user.boardgames.build
  end

  # GET /boardgames/1/edit
  def edit
  end

  # POST /boardgames or /boardgames.json
  def create
    #@boardgame = Boardgame.new(boardgame_params)
    @boardgame = current_user.boardgames.build(boardgame_params)

    respond_to do |format|
      if @boardgame.save
        format.html { redirect_to boardgame_url(@boardgame), notice: "Boardgame was successfully created." }
        format.json { render :show, status: :created, location: @boardgame }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @boardgame.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boardgames/1 or /boardgames/1.json
  def update
    respond_to do |format|
      if @boardgame.update(boardgame_params)
        format.html { redirect_to boardgame_url(@boardgame), notice: "Boardgame was successfully updated." }
        format.json { render :show, status: :ok, location: @boardgame }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @boardgame.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boardgames/1 or /boardgames/1.json
  def destroy
    @boardgame.destroy

    respond_to do |format|
      format.html { redirect_to boardgames_url, notice: "Boardgame was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @boardgame = current_user.boardgames.find_by(id: params[:id])
    redirect_to boardgames_path, notice: "Not authorized to edit this boardgame" if @boardgame.nil?    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_boardgame
      @boardgame = Boardgame.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def boardgame_params
      params.require(:boardgame).permit(:title, :author, :price, :rating, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boardgames_helper.rb
module BoardgamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/boardgames/_boardgame.html.erb
<div id="<%= dom_id boardgame %>">
  <p>
    <strong>Title:</strong>
    <%= boardgame.title %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= boardgame.author %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= boardgame.price %>
  </p>

  <p>
    <strong>Rating:</strong>
    <%= boardgame.rating %>
  </p>

</div>

app/views/boardgames/_form.html.erb
<%= form_with(model: boardgame) do |form| %>
  <% if boardgame.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(boardgame.errors.count, "error") %> prohibited this boardgame from being saved:</h2>

      <ul>
        <% boardgame.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :author, style: "display: block" %>
    <%= form.text_field :author %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :rating, style: "display: block" %>
    <%= form.text_field :rating %>
  </div>

  <div>
    <%= form.number_field :user_id, id: :boardgame_user_id, value: current_user.id, type: :hidden%>
  </div>

  <div>
    <%= form.submit class:"btn btn-secondary mt-2"%>
  </div>
<% end %>

app/views/boardgames/edit.html.erb
<h1>Editing boardgame</h1>

<%= render "form", boardgame: @boardgame %>

<br>

<div>
  <%= link_to "Show this boardgame", @boardgame %> |
  <%= link_to "Back to boardgames", boardgames_path %>
</div>

app/views/boardgames/index.html.erb
<p style="color: green"><%= notice %></p>

<% if user_signed_in? %>

  <h1>Boardgames</h1>

  <table class="table table-striped table-success">
      <thead>
        <th>Title</th>
        <th>Price</th>
        <th>Author</th>
        <th>Rating</th>
        <th>User Id</th>
        <th> </th>
      </thead>
      <tbody>
        <% @boardgames.each do |boardgame| %>
          <% if boardgame.user == current_user%>
          <tr>
            <td><%= boardgame.title %></td>
            <td><%= boardgame.price %></td>
            <td><%= boardgame.author%></td>
            <td><%= boardgame.rating%></td>
            <td><%= boardgame.user_id%></td>
            <td>
              <%= link_to "Show this boardgame", boardgame, class:"btn btn-secondary" %>
            </td>
          </tr>
          <% end %>
        <% end %>
      </tbody>
  </table>

  <%= link_to "New boardgame", new_boardgame_path, class:"btn btn-secondary" %>

<% else %>

<h1>Hello world</h1>
<p>Project voor ITalent</p>

<% end %>

app/views/boardgames/new.html.erb
<h1>Add new boardgame</h1>

<%= render "form", boardgame: @boardgame %>

<br>

<div>
  <%= link_to "Back to boardgames", boardgames_path %>
</div>

app/views/boardgames/show.html.erb
<div class="container-fluid">
  <p style="color: green"><%= notice %></p>

  <%= render @boardgame %>

  <div>
    <%= link_to "Edit this boardgame", edit_boardgame_path(@boardgame), class:"btn btn-secondary mr-2" %>
    <%= link_to "Back to boardgames", boardgames_path, class:"btn btn-secondary m-2" %>

    <br>
    <%= button_to "Destroy this boardgame", @boardgame, method: :delete, class:"btn btn-danger" %>
  </div>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
  <%= link_to 'Project App', root_path, class:"navbar-brand" %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Over Ons", home_about_path, class:"nav-link" %> 
        </li>
        <li class="nav-item">
          <%= link_to "Boardgames", boardgames_path, class:"nav-link" %> 
        </li>


        <% if user_signed_in? %>

          <li class="nav-item">
            <%= link_to "Voeg boardgame toe", new_boardgame_path, class:"nav-link" %> 
          </li>
          <li class="nav-item">
            <%= link_to "Profiel", edit_user_registration_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= button_to "Uitloggen", destroy_user_session_path, method: :delete, class:"nav-link" %>
          </li>

        <% else %>
          <li class="nav-item">
            <%= link_to "Aanmelden", new_user_registration_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Inloggen", new_user_session_path, class:"nav-link" %>
          </li>
        <% end %>

      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>Over ons</h1>

app/views/home/index.html.erb
<h1>Hello world</h1>
<p>Project voor ITalent</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project voor ITalent</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "home/header" %>
    <p class="notice"><%= notice %></p>
    <p class="alert alert"><%= alert %></p>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>